---
- hosts: servs
  become: yes
  tasks:
    - name: Install vsftpd
      apt:
        name:
         - vsftpd
        state: present

    - name: Populate service facts
      service_facts:

    - name: See the service <vsftp> facts as they are
      debug:
       msg: "{{ansible_facts.services['vsftpd.service'].state}}"