---
- name: RouterOS test with network_cli connection
  hosts: all
  gather_facts: true
  tasks:
    - name: Disable task
      routeros_command:
        commands: system scheduler disable Export_config_file_to_email

    - name: Show system schedulers
      routeros_command:
        commands: /system scheduler print
      register: system_scheduler_print

    - name: Show system schedulers
      debug:
        var: system_scheduler_print.stdout_lines

    - name: Show a fact
      debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"